# Thanks https://schnerring.net/blog/create-a-hugo-website-with-github-pages-github-actions-and-cloudflare/
# for the great tutorial on howto configure hugo with:
# - github pages
# - github actions (.github/workflows/hugo.yml)
# - cloudflare (scripts/purge_cloudflare_cache.sh)
baseURL = "https://patagon-ai.net/"
languageCode = "en"
title = "Patagon AI"
theme = "hugo-initio"

[params]
    name = "Patagon AI"
    description = "Patagon AI Tech"
    email = "info@patagon-ai.net"
    phone = "+1 (650) 204 1556"
    address = "8 The Green Ste B, Dover, Kent, Delaware 19901, USA"
    year = 2023
    avatar = "images/avatar.jpg"
    avatarclass = "circle"
    background = ""
    #banner = "images/bg_head.jpg"
    banner = "images/patagon_ai.png"
    favicon = "images/patagon_ai.ico"
    DateForm = "January 1, 2023"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
#[[menu.main]]
#    name = "blog"
#    url = "/posts/"
#    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

#[params.google.analytics]
#    trackerID = "GA-000000000-0"

#[[params.social]]
#    title = "facebook"
#    url = "https://www.facebook.com/nickname"
#    icon = "fab fa-facebook-square"
#    footer = true
#    sharethis = true
#    network = "facebook"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/PatagonAI"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
#[[params.social]]
#    title = "instagram"
#    url = "https://www.instagram.com/nickname"
#    icon = "fab fa-instagram"
#    footer = true
#    sharethis = false
#    network = ""
#[[params.social]]
#    title = "google+"
#    url = "https://plus.google.com/+nickname"
#    icon = "fab fa-google-plus-square"
#    footer = false
#    sharethis = true
#    network = "googleplus"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/company/patagon-ai"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
#[[params.social]]
#    title = "tumblr"
#    url = "https://nickname.tumblr.com"
#    icon = "fab fa-tumblr-square"
#    footer = false
#    sharethis = false
#    network = "tumblr"
#[[params.social]]
#    title = "github"
#    url = "https://github.com/nickname"
#    icon = "fab fa-github"
#    footer = true
#    sharethis = false
#    network = ""
[[params.social]]
    title = "email"
    url = "mailto:info@patagon-ai.net"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
